version: "3"

services:

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:8080"
        volumes:
            - ./frontend:/frontend

    backend:
        build:
            context: ./backend
        ports:
            - "80:3000"
        volumes:
            - ./backend:/app
        depends_on:
            - postgres
    
    postgres:
        image: postgres:16.4
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: task_tracker
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: